### ISSUE TITLE
Use current folder name as page title

### ISSUE THREAD

**Issue by hbons** [NewProggie/SparkleShare-Android#15]
except for the Overview, which can keep it's name "SparkleShare"

**Comment by hbons** [comment]
So this is almost right :)

In the topmost root:
"Projects" -> "SparkleShare"

 First subfolder root -> "Public Git Folder" (or whatever the name is)

**Comment by hbons** [comment]
Better explanation: https://github.com/hbons/SparkleShare-Design-Corner/raw/35a19243466ac5d0e09d9f32f8d2d225be5bef01/android/pages.png

**Comment by NewProggie** [comment]
Fixed now with e40a9ef717b5fc887b2f89b3cc4a5d971382a9ea
