### ISSUE TITLE
Move overview toolbar button

### ISSUE THREAD

**Issue by hbons** [NewProggie/SparkleShare-Android#23]
Let's move it to the outer right. Many apps seem to have no buttons on the left :)

**Comment by NewProggie** [comment]
It makes more sense to me to keep the overview (home) button on the left, since it is default since Android 3.0 as described here: http://developer.android.com/guide/topics/ui/actionbar.html

**Comment by hbons** [comment]
It doesn't say anything about keeping a button on the left, only the app logo (which we don't display).
It does speak about a drop-down list for navigation, which we can use instead.

**Comment by hbons** [comment]
Ok, so the conclusion from a chat we had:

Use "[SparkleShare icon] SparkeShare" on the top level overview and
"[folders icon] <current folder name>" when inside a folder.
