### ISSUE TITLE
Show domain/IP below overview folder name

### ISSUE THREAD

**Issue by hbons** [NewProggie/SparkleShare-Android#25]
Yep :)

**Comment by hbons** [comment]
Oh, also, let's use the grey folder. As we're already in the SparkleShare folder (the app). Just like the desktop clients all the project folders are normally styled.

**Comment by NewProggie** [comment]
Should the IP/domain name just be displayed on the root folder of each project?

**Comment by hbons** [comment]
correct

On 9 Oct 2011 11:49, "Kai Wolf" <
reply@reply.github.com>
wrote:

Should the IP/domain name just be displayed on the root folder of each
project?

##
