### ISSUE TITLE
Add "Upload..." item at end of list view

### ISSUE THREAD

**Issue by hbons** [NewProggie/SparkleShare-Android#36]
This would make the action more contextual to the folder contents.
It also allows us to remove the Upload button in the action bar to make it less crowded, but that does mean the user needs to scroll all the way down to upload a file. Something to think about.
Again no icon so it doesn't look like a file.

**Comment by NewProggie** [comment]
That's a difficult topic. It makes sense to me to keep all available actions in one place, so moving the upload button to the menu is not a good solution. I'm fine with two actions on the right of the action bar. Using an entry in the listview itself as an redundant option is also ok for me.
In general I have no idea how to upload files. Maybe we need to open up another issue server-sided for an appropriate API call:)

**Comment by hbons** [comment]
Personally I like an uncluttered action bar, but let's have both an see how people actually use it.
For 1.0, let's hide the upload button as it doesn't do anything yet. I will open and issue against Dashboard to get an upload API. :)
