### ISSUE TITLE
"dies" by tapping on Scan QR-Code

### ISSUE THREAD

**Issue by Jabajuh** [NewProggie/SparkleShare-Android#38]
The app closes if i tap on "Scan QR code".

Think its a problem with app authorization... there was none for camera when i installed it...

Tested on HTC Desire with MIUI 1.10.7

**Comment by hbons** [comment]
Happens for me as well on HTC Magic.

**Comment by NewProggie** [comment]
This is most likely caused by custom ROMs, as I am checking programmatically if a barcode scanner app (for scanning QR code) is installed on the phone. Otherwise the Scan QR Code button is disabled. I am going to double check now and commit the fix

**Comment by Jabajuh** [comment]
ok! fixed by installing the barcode scanner ("https://market.android.com/details?id=com.google.zxing.client.android&feature=search_result") app! ;)

**Comment by NewProggie** [comment]
Can you reproduce the bug with the Barcode Scanner app uninstalled?
Am 12.10.2011 21:10 schrieb "Jabajuh" <
reply@reply.github.com>:

**Comment by Jabajuh** [comment]
jep! its the same with barcode scanner uninstalled! 

Think you should tell the users that they have to install this (or another) app...
