### ISSUE TITLE
/api/getAuthCode name parameter

### ISSUE THREAD

**Issue by nextsux** [NewProggie/SparkleShare-Android#46]
I've added name parameter for device linking so device could be better identified later in dashboard. It would be nice to provide some from android app like device name or something like that

**Comment by hbons** [comment]
This woulod be good to have. We should also show the device linking code (or at least part of it) in the android app, so you can easily check which devices are linked to your server and identify any "rogue" devices.

**Comment by nextsux** [comment]
Not linking code - it's valid for only short time and is not stored persistently. I would suggest showing "ident" which is mandatory and let's say public identifier (but not nice). Name is meant to be nice, human-readable for device identification.

**Comment by hbons** [comment]
Yes, I meant to say the code that is used to identify the mobile client to the server.
