### ISSUE TITLE
Mark files for auto-sync

### ISSUE THREAD

**Issue by flamingspaz** [NewProggie/SparkleShare-Android#48]
Perhaps you could add files to auto sync as soon as they are changed. This would be useful to people using Password databases. You could make the app check for a new version every x minutes or use google's cloud server if that's possible.

**Comment by NewProggie** [comment]
This feature should be provided by the server as well. Generally I like this idea and will talk back to nextsux who writes the server backend.

**Comment by hbons** [comment]
So we've chosen to not actually "sync" anything automatically on the mobile clients for several reasons: 1. there's not really a file system the user interacts with, 2. Network access is unpredictable and costly. Mobile clients are more to cover "incidental use" as opposed to syncing everything on the fly on the desktop clients.
