### ISSUE TITLE
Not showing remote folders

### ISSUE THREAD

**Issue by rendered** [NewProggie/SparkleShare-Android#49]
I've set up the dashboard but I think I haven't configured the folders correctly in the config.js:

exports.folders = [
  { type: 'git', name: 'Development', path: '/sync/development.git', pub: false },
  { type: 'git', name: 'Documents', path: '/sync/documents.git', pub: false },
  { type: 'git', name: 'Pictures', path: '/sync/pictures.git', pub: false },
  { type: 'git', name: 'Share', path: '/sync/share.git', pub: false }
];

Does this look right - when I connect my Android to the server it connects but shows a blank screen?

**Comment by NewProggie** [comment]
This question is better asked in the issues section of SparkleShare-Dashboard: https://github.com/hbons/SparkleShare-Dashboard/issues

Unfortunately I can't forward this issue here, so please open up a new issue there.
