### ISSUE TITLE
Extended characters does not display correctly.

### ISSUE THREAD

**Issue by maghog** [NewProggie/SparkleShare-Android#50]
Extended characters does not display correctly.

Example: a directory created on a Linux workstation with the name "Sweåäö" will display as "Swe\303\245\303\244\303\266" in Dashboard and Andoid client.

Files containing extended characters cannot be opened in the Android client....

**Comment by nextsux** [comment]
this is more Dashboard bug, fixed in https://github.com/hbons/SparkleShare-Dashboard/commit/b2e2d56d87f4675b1b92ac41b9fee62053a02eef

**Comment by NewProggie** [comment]
great. Less work for me :-)

**Comment by nextsux** [comment]
that was quick :D

**Comment by maghog** [comment]
Yes, it works...thanx :-)
