### ISSUE TITLE
App crashes when nothing can open file

### ISSUE THREAD

**Issue by ghost** [NewProggie/SparkleShare-Android#58]
The logic that tries to anticipate this situation doesn't seem to work. When this happens the app dies on ActivityNotFoundException. I have updated the logic and it now works. It is this commit here:

https://github.com/andrewjbarr/SparkleShare-Android/commit/01027453fccab23305eecb8cb5378b205eb26977

I apologize (again) for being so ham-handed with git, but I cannot see how to enter this as a pull request without also including the commit I created to fix issue #57.

**Comment by NewProggie** [comment]
I will merge this commit manually as well.

**Comment by NewProggie** [comment]
Merged with b6e7e5e751029497ee6983d0961ac4d85fbfaa0b
