### ISSUE TITLE
Roadmap for OS support and Devices

### ISSUE THREAD

**Issue by gabrielstuff** [NewProggie/SparkleShare-Android#66]
Hi there,

Your software looks remarkly impressive.
Any roadmap for Windows integration ? iOS ? Windows 7 phone ?

Thank you,

Gabriel

**Comment by NewProggie** [comment]
Unfortunately not. I am not familiar with iOS and Windows programming.

**Comment by gabrielstuff** [comment]
ok, thanks.
Going to see how they feel here :
https://github.com/hbons/SparkleShare

thanks !
