### ISSUE TITLE
Cannot install on camera-less device

### ISSUE THREAD

**Issue by pfalcon** [NewProggie/SparkleShare-Android#68]
Due to way AndroidManifest.xml is written, SparkleShare-Android cannot be installed on device without camera (or at least Market and package manager filters it out from compatible list for such devices).

Use should add:

<uses-feature android:name="android.hardware.camera" android:required="false" />

to mark camera as optional, see right pane at http://developer.android.com/guide/topics/manifest/uses-permission-element.html for more info.

**Comment by NewProggie** [comment]
Are you talking about Google TV for example? If I remember correctly the Open Handset Alliance set up some requirements for device manufactures if they want to distribute Android on their devices. So a camera should be there.

**Comment by pfalcon** [comment]
I don't see how this is directly related. The problem is that SparkleShare-Android says (in its manifest) that it can't work without camera at all. Which is obviously not true - it merely could use a camera if it's available to scan an QR code.

Now answering your question, there're dozens of models of Android devices without a camera, and hundreds to appear, you can't name them all or imagine what they are/will be. Suffice to say that most fast-selling Android devices (who knows, maybe soon the most popular unique models of Android devices) - Kindle Fire and Nook Tablet - are without camera.

**Comment by NewProggie** [comment]
Never mind, I was just curious if there are devices without a camera. 
I will include a fix with the next update.

Thanks for bringing this to my attention
