### ISSUE TITLE
Build outside Google Play

### ISSUE THREAD

**Issue by Sixthhokage1** [NewProggie/SparkleShare-Android#83]
For devices that lack access to Google Play, it would be nice to have an APK downloadable elsewhere.

**Comment by rainulf** [comment]
It was in Google Play before. I wonder what happened.

**Comment by NewProggie** [comment]
@hbons rethinks the current strategy for mobile clients and asked me to remove it from the Google Play Store. You can still build the apk yourself and use ist.

**Comment by emanchado** [comment]
@NewProggie Is there any documentation on the rationale of that decision? Building my own .apk to install on my phone feels like way too much hassle. I can't even imagine what that would be like for any non-developer.

Or is the idea discontinuing SparkleShare-Android altogether?

**Comment by NewProggie** [comment]
@emanchado It wasn't my decision. So you better ask @hbons for his big idea ;-)

**Comment by lkwg82** [comment]
@NewProggie 

Are there any legal issues?

**Comment by NewProggie** [comment]
@lkwg82 not that I'm aware of

**Comment by pvledoux** [comment]
Hi guys, any updates about that? That's a bit sad that it's not available on Google Play any more.
